// This file was generated by counterfeiter
package test

import (
	uuid "github.com/satori/go.uuid"
)

const maxValidNameLength = 63

var TestOversizedNameObj = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl" // len=64 chars
var TestMaxsizedNameObj = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk"   // len=63 chars

// CreateRandomValidTestName functions creates a valid lenght name
func CreateRandomValidTestName(name string) string {
	randomName := name + uuid.NewV4().String()
	if len(randomName) > maxValidNameLength {
		return randomName[:maxValidNameLength]
	}
	return randomName
}
