BINARY_SERVER=alm.exe
BINARY_CLIENT=alm-cli.exe
GLIDE_BIN=glide.exe
GOAGEN_BIN=$(VENDOR_DIR)/github.com/goadesign/goa/goagen/goagen.exe
GO_BINDATA_BIN=$(VENDOR_DIR)/github.com/jteeuwen/go-bindata/go-bindata/go-bindata.exe
GO_BINDATA_ASSETFS_BIN=$(VENDOR_DIR)/github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs/go-bindata-assetfs.exe
FRESH_BIN=$(VENDOR_DIR)/github.com/pilu/fresh/fresh.exe
