= Deploying the Auth and WIT services on Minikube


== Creating the k8s objects for WIT and Auth

Once you have installed Minikube and `kubectl` (make sure you d/l the version that matches the k8s version), run the following commands to create all deployments, replica sets, pods and services in the default namespace:

````
# auth database
kubectl create -f fabric8-auth-db-deployment.yml,fabric8-auth-db-service.yml
# auth app
kubectl create -f fabric8-auth-deployment.yml,fabric8-auth-service.yml
# wit database
kubectl create -f fabric8-wit-db-deployment.yml,fabric8-wit-db-service.yml
# wit app
kubectl create -f fabric8-wit-deployment.yml,fabric8-wit-service.yml
````

Once all scripts passed, the Kubernetes objects will be avaiable:

````
> kubectl get all
NAME                                  READY     STATUS    RESTARTS   AGE
po/fabric8-auth-4268511339-tf1x3      1/1       Running   0          23m
po/fabric8-auth-db-2232448541-qb2st   1/1       Running   0          22m
po/fabric8-wit-920862249-66jgc        1/1       Running   0          17m
po/fabric8-wit-db-366674767-7g5p7     1/1       Running   0          21m

NAME                      CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
svc/fabric8-auth-db-svc   10.0.0.171   <none>        5432/TCP       24m
svc/fabric8-auth-svc      10.0.0.69    <nodes>       80:32089/TCP   5m
svc/fabric8-wit-db-svc    10.0.0.46    <none>        5432/TCP       21m
svc/fabric8-wit-svc       10.0.0.115   <nodes>       80:32080/TCP   5m

NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/fabric8-auth      1         1         1            1           23m
deploy/fabric8-auth-db   1         1         1            1           24m
deploy/fabric8-wit       1         1         1            1           21m
deploy/fabric8-wit-db    1         1         1            1           21m

NAME                            DESIRED   CURRENT   READY     AGE
rs/fabric8-auth-4268511339      1         1         1         23m
rs/fabric8-auth-db-2232448541   1         1         1         22m
rs/fabric8-wit-920862249        1         1         1         17m
rs/fabric8-wit-db-366674767     1         1         1         21m
````


Once the `kubectl create` commands for `auth` and `wit` have passed, you should be able to access the `auth` service on `http://$(minikube ip):32089`

````
> curl http://$(minikube ip):32089/api/status
{"buildTime":"2017-10-15T17:29:19Z","commit":"26e19df61b885a92774632f23bb5590c5f768a31","startTime":"2017-10-20T09:09:41Z"}
````

and the `wit` service on `http://$(minikube ip):32080`:

````
curl http://$(minikube ip):32080/api/status
{"buildTime":"2017-10-19T14:58:19Z","commit":"2a8fd6b0eace6fc17db9245b1dfda829534378a3","startTime":"2017-10-20T09:18:39Z"}
````

== Connecting to the services with custom hostnames

You can also connect to the `auth` and `wit` services using their respective service names using the following hack:

Add the following entries in `/etc/hosts`:

````
192.168.99.100 fabric8-auth-svc fabric8-wit-svc
````
(where `192.168.99.100` is the result of `minikube ip`)

then create an ingress for each service:

````
# enable the ingress addon
minikube addons enable ingress
# auth ingress
kubectl create -f fabric8-auth-ingress.yml,fabric8-auth-ingress.yml
````

From the host, you now have access to the service using:

````
> curl http://fabric8-wit-svc/api/status
{"buildTime":"2017-10-19T14:58:19Z","commit":"2a8fd6b0eace6fc17db9245b1dfda829534378a3","startTime":"2017-10-20T15:43:31Z"}
````

With the special configuration where the DNS entries match the k8s service names and the services use the port `80` internally and externally with the ingresses, we can have the same URLs for inter-services and browser-to-service communication.

== Using a custom namespace

Optionally, if you want to use a custom namespace for the Fabric8 services, you can run the following commands prior to the one above:

````
> kubectl create -f fabric8-namespace.yml

````

From now on, you can either use the `--namespace=fabric8` option to specify that the kubectl commands must run within the `fabric8` namespace, or you can set `fabric8` as the default namespace in the config context:

````
> kubectl config set-context $(kubectl config current-context) --namespace=fabric8
Context “minikube” modified.
````


