= Examples for using the CLI program with Work Item Types (WIT)

:toc:
:sectnums:
:experimental:

*Requirements:* Need token to use following API. Please go through link:https://github.com/fabric8-services/fabric8-wit/#3-developer-setup[README] to generate a token to use.

== Create an "Epic" Work Item Type

The following should fail as nothing is there (yet):

----
./bin/wit-cli show workitemtype --name "Epic" -H localhost:8080 --pp
----

Should create 1 WIT with `name=Epic`:

----
./bin/wit-cli create workitemtype --key "GENERATED_TOKEN" --payload '{"extendedTypeName":null,"fields":{"system_owner":{"type":{"kind":"user"},"required":true},"system_state":{"type":{"kind":"string"},"required":false}},"name":"Epic"}' -H localhost:8080 --pp
----

== Show newly created "Epic"

Should show you newly created item type:

----
./bin/wit-cli show workitemtype --name "Epic" -H localhost:8080 --pp
----

== Create "Issue" Work Item Type

Create another item type:

----
./bin/wit-cli create workitemtype --key "GENERATED_TOKEN" --payload '{"extendedTypeName":null,"fields":{"system_owner":{"type":{"kind":"user"},"required":true},"system_duration":{"type":{"kind":"integer"},"required":false}},"name":"Issue"}' -H localhost:8080 --pp
----

Retrieve newly created `Issue` work item type:

----
./bin/wit-cli show workitemtype --name "Issue" -H localhost:8080 --pp
----

Should fail - create item type based on pre-existing item type because `system_state` does not match to parent item type:

(The `system_state` must not be of type `float` but of type `string`.)

----
./bin/wit-cli create workitemtype --key "GENERATED_TOKEN" --payload '{"extendedTypeName":"Epic","fields":{"system_owner":{"type":{"kind":"user"},"required":true},"system_state":{"type":{"kind":"float"},"required":false}},"name":"anotherEpic"}' -H localhost:8080 --pp
----

Should create item type based on pre-existing item type:

(Now `system_state` has the correct type of `string`.)

----
./bin/wit-cli create workitemtype --key "GENERATED_TOKEN" --payload '{"extendedTypeName":"Epic","fields":{"system_owner":{"type":{"kind":"user"},"required":true},"system_state":{"type":{"kind":"string"},"required":false}},"name":"anotherEpic"}' -H localhost:8080 --pp
----

== List all work item types that we created

Should list all Work Item Types:

----
./bin/wit-cli list workitemtype -H localhost:8080 --pp
----
